--- 
- name: ping テスト
  win_ping:

- name: Temp ディレクトリ作成
  win_file:
    path: C:\Temp
    state: directory

- name: Push Open JDK.
  win_template:
    src: templates/ps_OpenJDK_Install.ps1.j2
    dest: C:\Temp\ps_OpenJDK_Install.ps1


# - name: Kick script
#   become: yes
#   become_user: "{{ azure_server_user }}"
#   win_shell: C:\Temp\ps_appInstall.ps1

