--- 
- name: ping テスト
  win_ping:

- name: Temp ディレクトリ作成
 - win_stat: path=c:\Temp
    register: dir_info
  - win_file:
      path: C:\Temp
      state: directory
    when: dir_info.exists == false

- name: Push Open JDK.
  win_template:
    src: templates/ps_OpenJDK_Install.ps1
    dest: C:\Temp\ps_appInstall.ps1


# - name: Kick script
#   become: yes
#   become_user: "{{ azure_server_user }}"
#   win_shell: C:\Temp\ps_appInstall.ps1

